services:
  classificatore_nps:
    build: ./ClassificatoreNPS
    container_name: clas_nps
    ports:
      - "8000:8000"
    restart: unless-stopped

  correction_dispersion:
    build: ./CorrectionDispersion
    container_name: correction_dispersion
    ports:
      - "8001:8001"
    restart: unless-stopped

  gaussian_puff:
    build: ./gaussianPuff
    container_name: gaussian_dispersion_model
    ports:
      - "8002:8002"
    restart: unless-stopped

  source_localization:
    build: ./EmissionSourceLocalization
    container_name: loc_emission_source
    ports:
      - "8003:8003"
    restart: unless-stopped

  correction_piml:
    build: ./CorrectionDispersion_PIML
    container_name: correction_dispersion_piml
    ports:
      - "8008:8008"
    restart: unless-stopped
    depends_on:
      - gaussian_puff
    volumes:
      - ./CorrectionDispersion_PIML:/CorrectionDispersion_PIML

  source_localization_piml:
    build: ./EmissionSourceLocalization_PIML
    container_name: loc_emission_source_piml
    ports:
      - "8010:8010"
    restart: unless-stopped
    depends_on:
      - gaussian_puff
    volumes:
      - ./EmissionSourceLocalization_PIML:/EmissionSourceLocalization_PIML

  pention_system:
    build: ./PentionSystem
    container_name: pention_system
    ports:
      - "8004:8004"
    restart: unless-stopped
    volumes:
      - ./gaussianPuff:/PentionSystem/gaussianPuff
      - ./ClassificatoreNPS:/PentionSystem/ClassificatoreNPS